services:
  mysql:
    image: mysql:8
    ports:
      - "${HOST_DB_PORT}:3306"
    restart: always
    volumes:
      - ddu-ru-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dduru
      TZ: Asia/Seoul
    profiles: [infra]
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks:
      - ddu-ru-network

  app:
    # image: ${DOCKER_IMAGE:-ddu-ru-backend:latest}
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${IMAGE_TAG}
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ddu-ru-app-logs:/app/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_HOST: mysql
      SPRING_DATASOURCE_USERNAME: ${MYSQL_ROOT_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      GOOGLE_ANDROID_CLIENT_ID: ${GOOGLE_ANDROID_CLIENT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      mysql:
        condition: service_healthy
    profiles: [app]
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 60s
    networks:
      - ddu-ru-network

volumes:
  ddu-ru-db-data:
  ddu-ru-app-logs:

networks:
  ddu-ru-network:
    driver: bridge
